name: build

on:
  push:
    branches: ["main"]

  pull_request:
  workflow_call:
    outputs:
      release_bundle:
        description: "Linux, MacOS, and Windows binaries"
        value: ${{jobs.build.outputs.artifact}}
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  build:
    name: Build Gawk binaries
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v5
      - run: |
          bazel run //:bundle_release -- bin/
      - name: smoke test
        run: ./bin/gawk_linux_amd64 --help
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'bin/gawk_*'
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: release_bundle
          retention-days: 1
          path: 'bin/gawk_*'
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: |
          bazel test --test_output=errors @gawk//...
