name: build

on:
  push:
    branches: ["main"]

  pull_request:
  workflow_call:
    outputs:
      windows:
        description: "Windows binaries"
        value: ${{jobs.build_windows.outputs.artifact}}
      linux:
        description: "Linux and MacOS binaries"
        value: ${{jobs.build.outputs.artifact}}
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  build:
    name: darwin and linux
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir bin
          bazel run //:install_all_unix -- bin/
      - name: smoke test
        run: ./bin/gawk_linux_amd64 --help
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'bin/gawk_*'
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: linux
          retention-days: 1
          path: 'bin/gawk_*'
  build_windows:
    name: windows
    runs-on: windows-2019
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir bin
          bazel run //:install_all_windows -- bin/
      - name: smoke test
        run: ./bin/gawk_windows_amd64.exe --help
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'bin/gawk_*'
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: windows
          retention-days: 1
          path: 'bin/gawk_*'
