name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build_all:
    uses: ./.github/workflows/build.yaml
  release:
    runs-on: ubuntu-latest
    needs: build_all
    steps:
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true
      - run: shasum -a 256 gawk_* > SHA256.txt
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            gawk_*
            SHA256.txt
